ktor:
  application:
    modules:
      - pl.ejdev.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  secret: "secret"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/api"
  realm: "UniResearchApi"
database:
#  url: "jdbc:postgresql://localhost/default"
#  user: username
#  password: password
  url: "${DB_URL}"
  user: "${DB_USER}"
  password: "${DB_PASS}"
  driver: "org.postgresql.Driver"